name: ukbrest
channels:
- defaults
- conda-forge
dependencies:
- coveralls=1.2.0
- coverage=4.5.1
- eventlet=0.21.0
- flask-restful=0.3.6
- ruamel.yaml=0.15.34
- beautifulsoup4=4.6.0
- flask=0.12.2
- gevent=1.2.2
- gunicorn=19.7.1
- html5lib=0.999999999
- ipython=6.2.1
- joblib=0.11
- lxml=4.1.1
- numpy=1.13.3
- pandas=0.21.0
- psycopg2=2.7.3.2
- python=3.6.3
- sqlalchemy=1.1.13
- sqlite=3.20.1
